// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2421.TankDrive;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CANJaguar;
import edu.wpi.first.wpilibj.RobotDrive;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANJaguar tankDriveSubsystemCANJaguar2;
    public static CANJaguar tankDriveSubsystemCANJaguar1;
    public static RobotDrive tankDriveSubsystemRobotDrive21;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        tankDriveSubsystemCANJaguar2 = new CANJaguar(1);
        LiveWindow.addActuator("TankDriveSubsystem", "CAN Jaguar 2", tankDriveSubsystemCANJaguar2);
        
        tankDriveSubsystemCANJaguar1 = new CANJaguar(0);
        LiveWindow.addActuator("TankDriveSubsystem", "CAN Jaguar 1", tankDriveSubsystemCANJaguar1);
        
        tankDriveSubsystemRobotDrive21 = new RobotDrive(tankDriveSubsystemCANJaguar1, tankDriveSubsystemCANJaguar2);
        
        tankDriveSubsystemRobotDrive21.setSafetyEnabled(true);
        tankDriveSubsystemRobotDrive21.setExpiration(0.1);
        tankDriveSubsystemRobotDrive21.setSensitivity(0.5);
        tankDriveSubsystemRobotDrive21.setMaxOutput(1.0);


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
